# Generated by Django 5.2.8 on 2026-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pendingemailverification_is_verified_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nomortelepon',
        ),
    ]
