# Generated by Django 5.2.6 on 2026-04-15 05:54

from django.db import migrations

# Coordinates for known BSD City / Banten area places.
# Matched by nama_tempat — only updates rows that currently have no coordinates.
_COORDS = [
    ("AEON Mall BSD City",                                                      -6.296234,  106.65321),
    ("Scientia Square Park (SQP Park)",                                         -6.231189,  106.651743),
    ("Ocean Park BSD City Serpong",                                             -6.203765,  106.618956),
    ("Indonesia Convention Exhibition (ICE) BSD City",                         -6.301012,  106.647432),
    ("Kopi Nako BSD",                                                           -6.301734,  106.655432),
    ("Hygge Cafe BSD",                                                          -6.305823,  106.678456),
    ("Bear&Butter BSD",                                                         -6.315731,  106.660687),
    ("Artirasa Gading Serpong",                                                 -6.230873,  106.645287),
    ("Bahasa Alam BSD",                                                         -6.309537,  106.671889),
    ("Salt Bread from Seoul BSD",                                               -6.314821,  106.661189),
    ("Funtasia by Minitopia (Playground & Children Museum) - Eastvara",        -6.317890,  106.643210),
    ("Playtopia Aeon Mall BSD City",                                            -6.296189,  106.653456),
    ("Meadow Terrace Sport Club - The Green BSD City",                         -6.308756,  106.670120),
    ("Sakura Park Aeon Mall BSD",                                               -6.296543,  106.653189),
    ("Padel;Parc Icon Clubhouse BSD",                                           -6.289012,  106.642678),
    ("Chinese Peranakan Library Museum",                                        -6.302345,  106.651234),
    ("National Museum of Indonesia",                                            -6.176469,  106.821838),
    ("Tugu Peringatan Proklamasi",                                              -6.208756,  106.830612),
]

# Handle the special character in "Rácquet" safely
_RACQUET_COORDS = (-6.298456, 106.651234)


def seed_coordinates(apps, schema_editor):
    Unggahan = apps.get_model("myapp", "Unggahan")
    for name, lat, lng in _COORDS:
        Unggahan.objects.filter(
            nama_tempat=name,
            latitude__isnull=True,
        ).update(latitude=lat, longitude=lng)

    # Rácquet Padel Club BSD — match by partial name to avoid encoding issues
    Unggahan.objects.filter(
        nama_tempat__icontains="cquet Padel",
        latitude__isnull=True,
    ).update(latitude=_RACQUET_COORDS[0], longitude=_RACQUET_COORDS[1])


def reverse_seed_coordinates(apps, schema_editor):
    # Reverse: clear the coordinates we set (only clears exact matches)
    Unggahan = apps.get_model("myapp", "Unggahan")
    for name, lat, lng in _COORDS:
        Unggahan.objects.filter(nama_tempat=name, latitude=lat, longitude=lng).update(
            latitude=None, longitude=None
        )
    Unggahan.objects.filter(
        nama_tempat__icontains="cquet Padel",
        latitude=_RACQUET_COORDS[0],
        longitude=_RACQUET_COORDS[1],
    ).update(latitude=None, longitude=None)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_savedtripplan'),
    ]

    operations = [
        migrations.RunPython(seed_coordinates, reverse_code=reverse_seed_coordinates),
    ]
